# Workflow to check PRs: lint, test, and bump version using conventional commits
name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  lint-test-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Bump version (conventional commits)
        uses: phips28/gh-action-bump-version@v10.1.1
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.merged == true
