name: 'Create Release'

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
